
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           /courses/postgrad/web
#relative_permalinks: true

# Setup
title:               'GEOG5870/1M: Web-based GIS'
tagline:             'A course on web-based mapping'
description:         'GEOG5870/1M: Web-based GIS, University of Leeds'
baseurl:     http://www.geog.leeds.ac.uk/courses/postgrad/web 
url:   http://www.geog.leeds.ac.uk/courses/postgrad/web    
 # http://massatleeds.github.io/webGIS/

# About/contact
author:
  name:             MASS Group
  url:              https://github.com/MassAtLeeds
  email:            a.j.evans@leeds.ac.uk

# Custom vars
version:             1.0.0

destination:         _site_wbg
layouts:     ./_layouts_wbg
exclude:     [atom.xml]


